#!/bin/bash
## VERSION= 1.0

## KISSB Wrapper script to start kissb using terminal without installation

## Specify version here
kissbChannel=dev 
kissbVersion=2024080402


kissbInstallFolder=.kb/install/${kissbChannel}
kissbRuntimePath=${kissbInstallFolder}/kissb-${kissbVersion}
if [[ ! -f ${kissbInstallFolder}/kissb-${kissbVersion} ]]
then
    # Download
    echo "Downloading KISSB runtime..."
    # Prepare local install folder and clean it
    rm -Rf .kb/install/*
    mkdir -p ${kissbInstallFolder}
    wget -q --show-progress https://kissb.s3.de.io.cloud.ovh.net/kissb/${kissbChannel}/kissb-${kissbVersion} -O ${kissbRuntimePath}
    chmod +x ${kissbRuntimePath}

    ## Check if this script is running from file
    if [[ $0 == '/bin/bash' ]]
    then
        echo "Downloading wrapper script..."
        wget -q https://github.com/richnou/kissb/raw/main/scripts/wrapper/kissbw
        chmod +x kissbw
    fi
fi

export KISSB_WRAPPER=1
${kissbRuntimePath} $*