site_name: KISSB Documentation
site_url: https://www.kissb.dev
nav:
  - ...

docs_dir: pages
plugins:
  - exclude:
      glob:
        - '**/~*'
  - drawio_file
  - search
  - table-reader:
      base_path: "docs_dir"
      data_path: "."
      search_page_directory: True
      allow_missing_files: True
  - kroki
  - git-revision-date
  - awesome-pages
  - include-markdown
  - mkdocstrings
  - glightbox
  - macros
  - social
  - privacy

repo_url: https://github.com/richnou/kissb
edit_uri: edit/main/docs/pages/
repo_name: Repository
extra_css:
theme:
  name: material
  #custom_dir: custom_theme/
  font:
    text: Baloo Chettan 2
  features:
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.action.edit
    - toc.integrate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - abbr
  - pymdownx.snippets
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: pymdownx.table
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      title: 'Table of Contents'
      toc_depth: '2-5'
      permalink: true
